{
 "title": "Chia Monitor",
 "description": "Displays all important metrics from your Chia farming node and all connected harvesters, collected by chia-monitor.",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "Pool",
    "query": {
     "query": "label_values(chia_current_pool_points, url)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Sync Status",
   "type": "stat",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chia_sync_status" }
   ]
  },
  {
   "title": "Unpaid Balance",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "XCH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sp_unpaid_balance_mojo/1e12" }
   ]
  },
  {
   "title": "Portable Plot Size Added",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    { "expr": "sum(chia_portable_plot_size)" }
   ]
  },
  {
   "title": "Portable Plot Count Added",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "plots" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    { "expr": "sum(chia_portable_plot_count)" }
   ]
  },
  {
   "title": "Total Farmed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "XCH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chia_farmed_total_mojos/1e12", "legendFormat": "Difficulty" }
   ]
  },
  {
   "title": "Total Balance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "XCH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chia_confirmed_total_mojos/1e12",
     "legendFormat": "Difficulty"
    }
   ]
  },
  {
   "title": "Reported Portable Plot Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sp_estimated_plot_size", "legendFormat": "Plot Size" }
   ]
  },
  {
   "title": "Reported Portable Plot",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "plots" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sp_estimated_plot_count", "legendFormat": "Plot Count" }
   ]
  },
  {
   "title": "Full Node Peers",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chia_connections_count{type=\"Full Node\"}"
    }
   ]
  },
  {
   "title": "Farmer Count",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chia_connections_count{type=\"Farmer\"}"
    }
   ]
  },
  {
   "title": "Harvester Count",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chia_connections_count{type=\"Harvester\"}"
    }
   ]
  },
  {
   "title": "Actual Portable Plot Size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(chia_portable_plot_size)", "legendFormat": "Plot Size" }
   ]
  },
  {
   "title": "Actual Portable Plot Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "plots" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(chia_portable_plot_count)", "legendFormat": "Plot Size" }
   ]
  },
  {
   "title": "Expected Time To Win",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "18.75 / ((sum(chia_plot_size) + sum(chia_portable_plot_size)) / sum(chia_network_space))",
     "legendFormat": "Plot Size"
    }
   ]
  },
  {
   "title": "Plot Size Delta",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A-$B", "type": "math" }
   ]
  },
  {
   "title": "Portable Plot Size Delta",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "plots" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$B-$A", "type": "math" }
   ]
  },
  {
   "title": "Chia Network Space",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chia_network_space", "legendFormat": "Netspace" }
   ]
  },
  {
   "title": "Average Daily Income",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "XCH" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "(chia_confirmed_total_mojos/1e12)/7",
     "legendFormat": "Difficulty"
    }
   ]
  },
  {
   "title": "Signage Points",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(chia_signage_points_total[5m]) * 60",
     "legendFormat": "Challanges"
    }
   ]
  },
  {
   "title": "Portable Plot Size Per Harvester",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chia_portable_plot_size", "legendFormat": "{{ host }}" }
   ]
  },
  {
   "title": "Peak Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chia_peak_height", "legendFormat": "Difficulty" }
   ]
  },
  {
   "title": "Farming Difficulty",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chia_diffculty", "legendFormat": "Difficulty" }
   ]
  },
  {
   "title": "Proofs Found",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "proof" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "round(increase(chia_proofs_found_total[10y]))",
     "legendFormat": "Difficulty"
    }
   ]
  },
  {
   "title": "Filters Passed",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(chia_plots_passed_filter_total[5m]) * 60",
     "legendFormat": "Filters Passed"
    }
   ]
  },
  {
   "title": "Contribution Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sp_pending_point/sp_global_pending_point",
     "legendFormat": "Difficulty"
    }
   ]
  },
  {
   "title": "Challenges",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(chia_block_challenges_total[5m]) * 60",
     "legendFormat": "Challanges"
    }
   ]
  },
  {
   "title": "Portable Plot Count Per Harvester",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "plots" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chia_portable_plot_count", "legendFormat": "{{ host }}" }
   ]
  },
  {
   "title": "XCH Price",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chia_price_usd_cent/100", "legendFormat": "Difficulty" }
   ]
  },
  {
   "title": "Total Balance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chia_price_usd_cent/100 * chia_confirmed_total_mojos/1e12",
     "legendFormat": "Difficulty"
    }
   ]
  },
  {
   "title": "Pending Point",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Pts" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sp_pending_point", "legendFormat": "Difficulty" }
   ]
  },
  {
   "title": "Pool Rank",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sp_rank", "legendFormat": "Difficulty" }
   ]
  },
  {
   "title": "Proofs Found",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(chia_proofs_found_total[5m]) * 60",
     "legendFormat": "Proofs"
    }
   ]
  },
  {
   "title": "Points Found 24h",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "points" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chia_pool_points_found_24h{url=\"$Pool\"}",
     "legendFormat": "Points"
    }
   ]
  },
  {
   "title": "Points Acknowledged 24h",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "points" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chia_pool_points_acknowledged_24h{url=\"$Pool\"}",
     "legendFormat": "Points"
    }
   ]
  },
  {
   "title": "Points Success Rate 24h",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chia_pool_points_acknowledged_24h{url=\"$Pool\"} / chia_pool_points_found_24h{url=\"$Pool\"}",
     "legendFormat": "Success Rate"
    }
   ]
  },
  {
   "title": "Pool Paid Balance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "XCH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sp_paid_balance_mojo/1e12", "legendFormat": "Difficulty" }
   ]
  },
  {
   "title": "Pool Difficulty",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chia_current_pool_difficulty{url=\"$Pool\"}",
     "legendFormat": "Difficulty"
    }
   ]
  },
  {
   "title": "Debt",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "USD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(chia_price_usd_cent/100 * chia_confirmed_total_mojos/1e12)-9999",
     "legendFormat": "Difficulty"
    }
   ]
  }
 ]
}