"""Add Space Pool table

Revision ID: b93090fcba20
Revises: 704c57c068fb
Create Date: 2021-08-01 20:02:04.827628

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'b93090fcba20'
down_revision = '704c57c068fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('space_pool_farmer_events',
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('unpaid_balance_mojos', sa.Integer(), nullable=True),
    sa.Column('paid_balance_mojos', sa.Integer(), nullable=True),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.Column('pending_points', sa.Integer(), nullable=True),
    sa.Column('global_pending_points', sa.Integer(), nullable=True),
    sa.Column('blocks_found', sa.Integer(), nullable=True),
    sa.Column('estimated_plot_size', sa.Integer(), nullable=True),
    sa.Column('estimated_plot_count', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('ts', name=op.f('pk_space_pool_farmer_events'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('space_pool_farmer_events')
    # ### end Alembic commands ###
